FROM node:20.5.0-alpine as base
ARG DEV_OPORT
WORKDIR /src

RUN [ "npm", "install", "-g", "npm@10.3.0" ]

FROM base as dev
COPY ./src/package*.json .
COPY ./src/next.config.js .
COPY ./src/tsconfig.json .
COPY ./src .
ENV NODE_ENV=development
ENV DEV_OPORT=DEV_OPORT

CMD [ "npm","run", "dev"]
