version: '3.8'
services:
    base:
        build:
            context: .
            target: base
            dockerfile: ./Dockerfile.dev
        image: node_base
        volumes:
            - type: bind
              source: ./src
              target: /src
        entrypoint: ['npx', '-y', 'create-next-app', '.']
        command:
            [
                '--ts',
                '--tailwind',
                '--eslint',
                '--app',
                '--no-src-dir',
                '--import-alias',
                '@/*'
            ]
    installer:
        build:
            context: .
            target: base
            dockerfile: ./Dockerfile.dev
        image: node_base
        volumes:
            - type: bind
              source: ./src
              target: /src
        entrypoint: ['npm', 'install']
        command: [
                '@reduxjs/toolkit',
                'react-redux',
                'redux',
                'next-redux-wrapper',
                'prettier',
                'eslint-config-prettier',
                'nrstate'
                # '@tailwindcss/jit'
            ] # package
