version: '3.8'
services:
    app:
        container_name: front-app-prod
        image: front-app-prod
        build:
        context: .
        dockerfile: Dockerfile.prod
        args:
            ENV_VARIABLE: ${ENV_VARIABLE}
            NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        restart: always
        ports:
            - 4400:4400
