FROM node:20.4.0-bookworm-slim as base
WORKDIR /src
COPY src ./src
FROM base as app
ENV NODE_ENV=development
COPY ./src/package*.json ./
COPY next.config.js .
COPY tsconfig.json .
RUN [ "npm", "install" ]
CMD ["npm", "run", "dev"]
