version: '3.8'
services:
    app:
        build:
            context: .
            target: dev
            dockerfile: Dockerfile.dev
        image: next-app
        container_name: next-app
        env_file:
            - .env.dev
        volumes:
            - type: bind
              source: ./src
              target: /src

            - type: volume
              source: node_modules
              target: /src/node_modules
        ports:
            - 3000:3000
        restart: always
        tty: true
        stdin_open: true
        environment:
            # - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - DEV_PORT=3007
volumes:
    node_modules:
