import React from 'react'
import { Provider } from 'react-redux'
import ReduxProvider from '@/store/provider'
// import { fetchUserData } from '@/features/user/api'
import { login, logout } from '@/features/user/store/slice'

import store from '@/store'
import { userDataThunk } from '@/features/user/store/slice'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}
export default async function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    // const { store, props } = wrapper.useWrappedStore({})

    // console.log(8888)

    const create = async () => {
        'use server'
        console.log(7878787)
        userDataThunk()
        // await new Promise((resolve) => setTimeout(resolve, 5000))
    }
    create()

    // console.log(ttt)

    // await new Promise((resolve) => setTimeout(resolve, 5000))

    return (
        <html lang='jp'>
            <body>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    )
}
// RootLayout.getInitialProps = async () => {}
